export class cardData {
  static data = {
    policy: "CG-MED-37",
    policy_html:
      "https://www.anthem.com/dam/medpolicies/abcbs_va/active/guidelines/gl_pw_c107909.html",
    cards: [
      {
        id: "card_1",
        card: "an evaluation* to confirm a suspected diagnosis of pediatric feeding disorder\u2020 is considered medically necessary",
        para_coords: [125, 813, 1042, 858],
        page: 1,
        sub_cards: [
          [
            {
              id: "card_1_1.1",
              card: "evaluation * to confirm a suspected diagnosis of pediatric feeding disorder\u2020",
              entities: ["pediatric feeding disorder"],
              include: true,
              logic: "and",
              para_coords: [125, 813, 1042, 858],
              para_coords_ori: [125, 813, 1042, 858],
              para_pointsize: 0,
            },
          ],
          [
            {
              id: "card_1_2.1",
              card: "children whose difficulties began under five ( 5 ) years of age who meet either of following criteria",
              entities: [],
              include: true,
              logic: "and",
            },
          ],
          [
            [
              {
                id: "card_1_3_1.1",
                card: "failure to meet developmental milestones of growth and development",
                entities: ["failure"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_1_3_2.1",
                card: "significant weight loss",
                entities: ["significant weight loss"],
                include: true,
                logic: "and",
              },
              {
                id: "card_1_3_2.2",
                card: "reduction or cessation of weight gain",
                entities: ["reduction", "weight gain"],
                include: true,
                logic: "and",
              },
              {
                id: "card_1_3_2.3",
                card: "previous 2 months",
                entities: [],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_1_3_3.1",
                card: "growth and development milestones have been met , but only via nutritional support consisting of high-calorie foods , nutritionally deficient foods , or both ,",
                entities: ["nutritional support"],
                include: true,
                logic: "and",
              },
              {
                id: "card_1_3_3.2",
                card: "transition to nutritionally and calorically appropriate foods is warranted",
                entities: ["nutritionally and calorically appropriate foods"],
                include: true,
                logic: "or",
              },
            ],
          ],
        ],
        include: true,
      },
      {
        id: "card_2",
        card: "an evaluation* to confirm a suspected diagnosis of pediatric feeding disorder\u2020 is considered medically necessary",
        sub_cards: [
          [
            {
              id: "card_2_1.1",
              card: "evaluation * to confirm a suspected diagnosis of pediatric feeding disorder\u2020",
              entities: ["pediatric feeding disorder"],
              include: true,
              logic: "and",
            },
          ],
          [
            [
              {
                id: "card_2_2_1.1",
                card: "severe , complex neurologic or neuromuscular disorders are present and are felt to be contributing to failure in meeting developmental milestones of growth and development , including either of following",
                entities: [
                  "severe , complex neurologic or neuromuscular disorders",
                  "failure",
                ],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_2_2_2.1",
                card: "reduction or cessation of weight gain",
                entities: ["reduction", "weight gain"],
                include: true,
                logic: "and",
              },
              {
                id: "card_2_2_2.2",
                card: "previous 2 months",
                entities: [],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_2_2_3.1",
                card: "significant change in feeding behavior is felt to be compromising child \u2019s nutritional status , including any of following",
                entities: ["significant change in feeding behavior"],
                include: true,
                logic: "or",
              },
            ],
          ],
          [
            [
              {
                id: "card_2_2_3_1.1",
                card: "reduction or cessation of weight gain",
                entities: ["reduction", "weight gain"],
                include: true,
                logic: "and",
              },
              {
                id: "card_2_2_3_1.2",
                card: "previous 2 months",
                entities: [],
                include: true,
                logic: "or",
              },
            ],
          ],
          [
            [
              {
                id: "card_2_2_3_4_1.1",
                card: "including neurologic , metabolic and gastrointestinal ( specifically malabsorption and gastroesophageal reflux disease ) clinical nutritional work-up as indicated",
                entities: [
                  "neurologic , metabolic and gastrointestinal ( specifically malabsorption",
                  "gastroesophageal reflux disease",
                ],
                include: true,
                logic: "and",
              },
            ],
            [
              {
                id: "card_2_2_3_4_2.1",
                card: "evaluation",
                entities: [],
                include: true,
                logic: "and",
              },
              {
                id: "card_2_2_3_4_2.2",
                card: "identify any structural or functional abnormalities",
                entities: ["any structural or functional abnormalities"],
                include: true,
                logic: "and",
              },
            ],
            [
              {
                id: "card_2_2_3_4_3.1",
                card: "evaluation of possible behavioral components",
                entities: ["behavioral components"],
                include: true,
                logic: "or",
              },
            ],
          ],
          [
            {
              id: "card_3_1.1",
              card: "\u2020possible situations that could initiate an evaluation for a pediatric feeding disorder",
              entities: [" pediatric feeding disorder"],
              include: true,
              logic: "or",
            },
          ],
          [
            [
              {
                id: "card_3_2_1.1",
                card: "coughs , chokes or gags while eating or immediately after eating",
                entities: ["coughs", "gags"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_3_2_2.1",
                card: "demonstrates a history of chronic pulmonary difficulties which may include diagnosis of aspiration pneumonia",
                entities: [
                  "chronic pulmonary difficulties",
                  "aspiration pneumonia",
                ],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_3_2_3.1",
                card: "dysfunction",
                entities: ["dysfunction"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_3_2_4.1",
                card: "weight gain is poor and difficult",
                entities: ["weight gain"],
                include: true,
                logic: "and",
              },
              {
                id: "card_3_2_4.2",
                card: "thought to be secondary to an oral-sensorimotor , pharyngeal , or swallowing dysfunction",
                entities: [
                  " oral-sensorimotor , pharyngeal",
                  "swallowing dysfunction",
                ],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_3_2_5.1",
                card: "difficulty",
                entities: ["difficulty"],
                include: true,
                logic: "and",
              },
              {
                id: "card_3_2_5.2",
                card: "initiating a swallow",
                entities: [" swallow"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_3_2_6.1",
                card: "structural abnormalities are present that may interfere with development of a normal swallow",
                entities: ["structural abnormalities"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_3_2_7.1",
                card: "chronic food refusal",
                entities: ["chronic food refusal"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_3_2_8.1",
                card: "excessive length of time getting child to eat",
                entities: [],
                include: true,
                logic: "and",
              },
              {
                id: "card_3_2_8.2",
                card: "meals lasting greater than 30 minutes",
                entities: [],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_3_2_9.1",
                card: "neuromotor involvement",
                entities: ["neuromotor involvement"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_3_2_10.1",
                card: "chronic poor growth",
                entities: ["chronic poor growth"],
                include: true,
                logic: "and",
              },
              {
                id: "card_3_2_10.2",
                card: "compromised nutritional status",
                entities: ["compromised nutritional status"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_3_2_11.1",
                card: "difficulties",
                entities: ["difficulties"],
                include: true,
                logic: "and",
              },
              {
                id: "card_3_2_11.2",
                card: "transitioning from tube or gastrostomy tube feedings to oral feedings",
                entities: [
                  "tube",
                  "gastrostomy tube feedings",
                  "oral feedings",
                ],
                include: true,
                logic: "or",
              },
            ],
          ],
        ],
        include: true,
      },
      {
        id: "card_4",
        card: "a reevaluation is considered medically necessary",
        sub_cards: [
          [
            {
              id: "card_4_1.1",
              card: "reevaluation",
              entities: [],
              include: true,
              logic: "and",
            },
          ],
          [
            [
              {
                id: "card_4_2_1.1",
                card: "new clinical findings",
                entities: ["new clinical findings"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_4_2_2.1",
                card: "rapid change",
                entities: ["rapid change"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_4_2_3.1",
                card: "failure",
                entities: ["failure"],
                include: true,
                logic: "and",
              },
              {
                id: "card_4_2_3.2",
                card: "respond to therapy interventions ( for example speech and language , occupational therapy , physical , and behavioral therapy )",
                entities: [
                  "therapy interventions",
                  "speech",
                  "occupational therapy",
                  "behavioral therapy",
                ],
                include: true,
                logic: "or",
              },
            ],
          ],
        ],
        include: true,
      },
      {
        id: "card_5",
        card: "note:",
        sub_cards: [
          [
            {
              id: "card_5_1.1",
              card: "several routine reassessments that are not considered reevaluations",
              entities: [],
              include: true,
              logic: "and",
            },
            {
              id: "card_5_1.2",
              card: "reevaluation is a more comprehensive assessment that usually includes components of initial evaluation , and may also include components such as",
              entities: [],
              include: true,
              logic: "and",
            },
          ],
          [
            [
              {
                id: "card_5_2_1.1",
                card: "data collection",
                entities: [],
                include: true,
                logic: "and",
              },
              {
                id: "card_5_2_1.2",
                card: "objective measurements taken based on appropriate and relevant assessment tests and tools using comparable and consistent methods",
                entities: [],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_5_2_2.1",
                card: "organizing composite of current problem areas and deciding a priority/focus of treatment",
                entities: [],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_5_2_3.1",
                card: "revision in plan of care",
                entities: ["revision"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_5_2_4.1",
                card: "meaningful change in function",
                entities: ["meaningful change in function"],
                include: true,
                logic: "or",
              },
            ],
            [
              {
                id: "card_5_2_5.1",
                card: "effectiveness of intervention(s )",
                entities: ["intervention(s"],
                include: true,
                logic: "or",
              },
            ],
          ],
        ],
        include: true,
      },
      {
        id: "card_6",
        card: "the treatment of a pediatric feeding disorder is considered medically necessary",
        sub_cards: [
          [
            {
              id: "card_6_1.1",
              card: "treatment of a pediatric feeding disorder",
              entities: [" pediatric feeding disorder"],
              include: true,
              logic: "and",
            },
          ],
          [
            {
              id: "card_6_2.1",
              card: "disorder has been diagnosed after appropriate evaluation and all of following criteria are met",
              entities: ["disorder"],
              include: true,
              logic: "and",
            },
          ],
          [
            [
              {
                id: "card_6_3_1.1",
                card: "thorough medical evaluation",
                entities: [],
                include: true,
                logic: "and",
              },
            ],
            [
              {
                id: "card_6_3_2.1",
                card: "adequate treatment for any contributing underlying medical conditions",
                entities: [
                  "adequate",
                  "any contributing underlying medical conditions",
                ],
                include: true,
                logic: "and",
              },
              {
                id: "card_6_3_2.2",
                card: "occurred without resolution of feeding problem",
                entities: ["feeding problem"],
                include: true,
                logic: "and",
              },
            ],
            [
              {
                id: "card_6_3_3.1",
                card: "treatment plan , individualized to each child , is developed and includes diagnosis , problem list , proposed treatment plan with specific interventions , and estimated length of treatment",
                entities: ["plan", "specific interventions"],
                include: true,
                logic: "or",
              },
            ],
          ],
        ],
        include: true,
      },
      {
        id: "card_7",
        card: "note:",
        sub_cards: [
          [
            {
              id: "card_7_1.1",
              card: "issues that may be addressed",
              entities: [],
              include: true,
              logic: "and",
            },
            {
              id: "card_7_1.2",
              card: "include specific dietary interventions or special formulas , positioning during feeding , behavioral interventions and family or caregiver education",
              entities: [
                "specific dietary interventions",
                "special formulas",
                "positioning during feeding",
                "behavioral interventions",
              ],
              include: true,
              logic: "and",
            },
            {
              id: "card_7_1.3",
              card: "intensity of treatment may vary from short-term intermittent outpatient visits to more intensive treatment programs",
              entities: ["intensive programs"],
              include: true,
              logic: "and",
            },
            {
              id: "card_7_1.4",
              card: "inpatient or intensive outpatient treatment programs may be warranted for severe cases , such as malnutrition or failure to thrive , unstable electrolyte disorders , potentially serious allergic reactions to food , significant difficulty transitioning from tube feedings to oral feedings , etc",
              entities: [
                "intensive outpatient programs",
                "severe cases",
                "malnutrition",
                "failure to thrive",
                "unstable electrolyte disorders",
                "serious allergic reactions",
                "tube feedings",
                "oral feedings",
              ],
              include: true,
              logic: "and",
            },
          ],
        ],
        include: true,
      },
      {
        id: "card_8",
        card: "note:",
        sub_cards: [
          [
            {
              id: "card_8_1.1",
              card: "individuals receive concurrent physical , occupational , behavioral , or speech therapy",
              entities: ["speech therapy"],
              include: true,
              logic: "and",
            },
            {
              id: "card_8_1.2",
              card: "provide different treatments that reflect each therapy discipline 's unique perspective on individual 's impairments and functional deficits and not duplicate same treatment . they must also have separate evaluations , treatment plans , and goals",
              entities: [
                "different treatments",
                "each therapy",
                "individual 's impairments",
                "functional deficits",
                "same plans",
              ],
              include: true,
              logic: "and",
            },
          ],
        ],
        include: true,
      },
    ],
    decision_logic: {
      card_1:
        "( card_1_1.1 ) and( card_1_2.1 ) and( ( card_1_3_1.1 ) or( card_1_3_2.1 and card_1_3_2.2 and card_1_3_2.3 ) or( card_1_3_3.1 and card_1_3_3.2 ) )",
      card_2:
        "( card_2_1.1 ) and( ( card_2_2_1.1 ) or( card_2_2_2.1 and card_2_2_2.2 ) or( card_2_2_3.1 ) ) or( ( card_2_2_3_1.1 and card_2_2_3_1.2 ) ) or( ( card_2_2_3_4_1.1 ) and( card_2_2_3_4_2.1 and card_2_2_3_4_2.2 ) and( card_2_2_3_4_3.1 ) ) or( card_3_1.1 ) or( ( card_3_2_1.1 ) or( card_3_2_2.1 ) or( card_3_2_3.1 ) or( card_3_2_4.1 and card_3_2_4.2 ) or( card_3_2_5.1 and card_3_2_5.2 ) or( card_3_2_6.1 ) or( card_3_2_7.1 ) or( card_3_2_8.1 and card_3_2_8.2 ) or( card_3_2_9.1 ) or( card_3_2_10.1 and card_3_2_10.2 ) or( card_3_2_11.1 and card_3_2_11.2 ) )",
      card_4:
        "( card_4_1.1 ) and( ( card_4_2_1.1 ) or( card_4_2_2.1 ) or( card_4_2_3.1 and card_4_2_3.2 ) )",
      card_5:
        "( card_5_1.1 and card_5_1.2 ) and( ( card_5_2_1.1 and card_5_2_1.2 ) or( card_5_2_2.1 ) or( card_5_2_3.1 ) or( card_5_2_4.1 ) or( card_5_2_5.1 ) )",
      card_6:
        "( card_6_1.1 ) and( card_6_2.1 ) and( ( card_6_3_1.1 ) and( card_6_3_2.1 and card_6_3_2.2 ) and( card_6_3_3.1 ) )",
      card_7: "( card_7_1.1 and card_7_1.2 and card_7_1.3 and card_7_1.4 )",
      card_8: "( card_8_1.1 and card_8_1.2 )",
      final_decision:
        "card_1 | card_2 | card_4 | card_5 | card_6 | card_7 | card_8",
    },
    synonyms: {
      "pediatric feeding disorder": {
        labels: "PROBLEM",
        synonyms: [
          "feeding disorders",
          "choking",
          "gagging",
          "vomiting",
          "",
          "pediatric feeding disorder",
          "pediatric feeding disorders",
          "comprehensive pediatric feeding program",
          "a pediatric feeding disorder",
          "poor feeding\nautosomal dominant dilated cardiomyopathy \ntype 1r",
          "food allergy profile",
          "a comprehensive pediatric feeding program",
        ],
      },
      failure: {
        labels: "PROBLEM",
        synonyms: [
          "feeding disorders",
          "choking",
          "gagging",
          "vomiting",
          "",
          "heart failure",
        ],
      },
      "significant weight loss": {
        labels: "PROBLEM",
        synonyms: [
          "a feeding problem",
          "chronic conditions",
          "feeding disorders",
          "",
          "abdominal pain",
          "wt loss",
        ],
      },
      reduction: {
        labels: "TREATMENT",
        synonyms: [
          "pediatric feeding disorder\u2020 reduction",
          "eating disorders",
          "",
          "crossing 2",
        ],
      },
      "weight gain": {
        labels: "PROBLEM",
        synonyms: [
          "extreme weight gain",
          "rapid weight gain",
          "a feeding problem",
          "unexplained weight gain",
          "",
          "a thorough medical evaluation",
          "weight gain",
          "her bmi",
        ],
      },
      "nutritional support": {
        labels: "TREATMENT",
        synonyms: [
          "feeding disorders",
          "feeds disease",
          "chronic conditions",
          "a chronic pediatric feeding disorder",
          "",
          "clinical nutritional work",
          "clinical nutritional work-up",
          "primary nutrition",
          "nutritional assessments",
        ],
      },
      "nutritionally and calorically appropriate foods": {
        labels: "TREATMENT",
        synonyms: ["feeding disorders", "", "increased calories"],
      },
      "severe , complex neurologic or neuromuscular disorders": {
        labels: "PROBLEM",
        synonyms: ["", ""],
      },
      "significant change in feeding behavior": {
        labels: "PROBLEM",
        synonyms: [
          "a feeding problem",
          "chronic conditions",
          "feeding disorders",
          "",
          "head turning",
          "some vomiting",
          "sustained hemorrhagic hydrocephalus",
          "significant change in feeding behavior",
          "sustained hemorrhagic hydrocephalous",
        ],
      },
      "neurologic , metabolic and gastrointestinal ( specifically malabsorption":
        {
          labels: "PROBLEM",
          synonyms: [
            "pediatric feeding  disorders",
            "",
            "gi eval",
            "neurologic, metabolic and gastrointestinal (specifically malabsorption",
            "med nec",
            "comorbid is arfid",
            "vitamin d, celiac, esr",
          ],
        },
      "gastroesophageal reflux disease": {
        labels: "PROBLEM",
        synonyms: [
          "a dry cough",
          "trouble swallowing",
          "burping",
          "belching",
          "stomach pain",
          "vomiting",
          "hiccups",
          "gagging",
          "choking",
          "gerd (gastroesophageal reflux disease)",
          "",
          "gastroesophageal reflux disease",
          "eating disorders",
          "gerd (gastroesophageal reflux disease)",
        ],
      },
      "any structural or functional abnormalities": {
        labels: "PROBLEM",
        synonyms: [
          "feeding problems",
          "",
          "any structural or functional abnormalities",
          "appropriate evaluation",
          "functional or structural abnormalities",
        ],
      },
      "behavioral components": {
        labels: "PROBLEM",
        synonyms: ["", "", "behavioral components", "behavioral eval"],
      },
      " pediatric feeding disorder": {
        labels: "PROBLEM",
        synonyms: ["pediatric feeding  disorders", ""],
      },
      coughs: {
        labels: "PROBLEM",
        synonyms: [
          "coughing",
          "gagging",
          "difficulty chewing",
          "difficulty breathing",
          "",
        ],
      },
      gags: { labels: "PROBLEM", synonyms: ["", "", "mp/cg"] },
      "chronic pulmonary difficulties": {
        labels: "PROBLEM",
        synonyms: [
          "pediatric dysphagia",
          "feeding disorders",
          "",
          "pulmonary hyperinflation",
          "cdc charts",
          "acute on\nchronic heart failure",
          "acute on chronic heart failure",
        ],
      },
      "aspiration pneumonia": {
        labels: "PROBLEM",
        synonyms: [
          "aspiration",
          "coughing",
          "difficulty feeding",
          "frequent respiratory infections",
          "recurrent pneumonia",
          "noisy breathing",
          "gagging",
          "back arching",
          "",
          "aspiration into airway",
        ],
      },
      dysfunction: {
        labels: "PROBLEM",
        synonyms: [
          "a pediatric feeding disorder",
          "coughing",
          "gagging",
          "difficulty breastfeeding",
          "frequent spitting",
          "vomiting",
          "irritable",
          "slow weight gain",
          "",
          "global delay",
          "a delay",
          "poor transition",
        ],
      },
      " oral-sensorimotor , pharyngeal": {
        labels: "PROBLEM",
        synonyms: [
          "pediatric dysphagia",
          "feeding disorders",
          "pharyngeal dysphagia",
          "down syndrome",
          "",
          "oral motor exercises",
          "op oral therapy",
        ],
      },
      "swallowing dysfunction": {
        labels: "PROBLEM",
        synonyms: [
          "breathing difficulties",
          "coughing",
          "choking",
          "crying",
          "decreased responsiveness",
          "",
          "trouble swallowing",
        ],
      },
      difficulty: {
        labels: "PROBLEM",
        synonyms: [
          "a problem",
          "vomiting",
          "diarrhea",
          "tummy aches",
          "this problem",
          "pediatric feeding disorders",
          "",
        ],
      },
      " swallow": {
        labels: "TREATMENT",
        synonyms: [
          "swallowing disorders",
          "dysphagia",
          "trouble during the swallowing process",
          "",
          "upper gi",
          "gi evaluation",
          "video swallow study",
          "poor oral intake",
          "an ugi",
        ],
      },
      "structural abnormalities": {
        labels: "PROBLEM",
        synonyms: [
          "pediatric dysphagia",
          "feeding disorders",
          "",
          "structural abnormalities",
          "visual appearance",
          "abnormal chest ct",
        ],
      },
      "chronic food refusal": {
        labels: "PROBLEM",
        synonyms: [
          "",
          "",
          "food refusal",
          "refusal behaviors",
          "oral aversion",
          "her constipation",
          "fecal cal protectin",
        ],
      },
      "neuromotor involvement": {
        labels: "PROBLEM",
        synonyms: ["cerebral palsy", ""],
      },
      "chronic poor growth": {
        labels: "PROBLEM",
        synonyms: [
          "chronic conditions",
          "a feeding problem",
          "feeding disorders",
          "",
          "poor growth",
          "chronic heart failure",
          "chronic gastritis",
          "the growth charts",
        ],
      },
      "compromised nutritional status": {
        labels: "PROBLEM",
        synonyms: ["feeding disorders", "pediatric dysphagia", ""],
      },
      difficulties: {
        labels: "PROBLEM",
        synonyms: ["pediatric feeding  disorders", ""],
      },
      tube: {
        labels: "TREATMENT",
        synonyms: [
          "dysphagia",
          "a feeding disorder",
          "",
          "ng tube",
          "the eval",
          "home o2",
          "ng tube dependent",
          "the pump",
          "a g-tube",
          "a vp shunt",
        ],
      },
      "gastrostomy tube feedings": {
        labels: "TREATMENT",
        synonyms: [
          "gastrostomy tube",
          "",
          "gastrostomy tube placement",
          "a gastrostomy tube",
        ],
      },
      "oral feedings": {
        labels: "TREATMENT",
        synonyms: [
          "",
          "",
          "oral feeds",
          "an interdisciplinary feeding\nevaluation",
          "enteral feedings",
          "oral feedings",
        ],
      },
      "new clinical findings": {
        labels: "PROBLEM",
        synonyms: ["ischemic colitis", ""],
      },
      "rapid change": { labels: "PROBLEM", synonyms: ["", ""] },
      "therapy interventions": {
        labels: "TREATMENT",
        synonyms: [
          "a reevaluation therapy interventions",
          "a quick scan",
          "follow\u2010up study",
          "",
        ],
      },
      speech: {
        labels: "TREATMENT",
        synonyms: ["", "", "sensory integration"],
      },
      "occupational therapy": {
        labels: "TREATMENT",
        synonyms: [
          "a reevaluation occupational therapy",
          "a quick scan",
          "",
          "occupational therapy",
        ],
      },
      "behavioral therapy": {
        labels: "TREATMENT",
        synonyms: [
          "a reevaluation behavioral therapy",
          "a quick scan",
          "cognitive behavior therapy",
          "anxiety",
          "depression",
          "behavioral therapies",
          "",
        ],
      },
      revision: {
        labels: "TREATMENT",
        synonyms: ["revision alteration", "reexamination", "", "vp shunt"],
      },
      "meaningful change in function": {
        labels: "PROBLEM",
        synonyms: [
          "significant change",
          "esketamine iv efficacy",
          "esketamine nasal spray",
          "oral antidepressant madrs scale sustain-",
          "esketamine",
          "",
        ],
      },
      "intervention(s": { labels: "TREATMENT", synonyms: ["intervention", ""] },
      disorder: {
        labels: "PROBLEM",
        synonyms: [
          "clinical depression",
          "anxiety disorder",
          "bipolar disorder",
          "dementia",
          "attention deficit hyperactivity disorder",
          "schizophrenia",
          "obsessive compulsive disorder (ocd)",
          "autism  and  post-traumatic stress disorder",
          "",
          "a disorder",
          "metabolic condition",
          "sensory integration disorder",
        ],
      },
      adequate: {
        labels: "TREATMENT",
        synonyms: [
          "feeding disorders",
          "a feeding disorder",
          "an eating disorder",
          "",
          "adequate treatment",
        ],
      },
      "any contributing underlying medical conditions": {
        labels: "PROBLEM",
        synonyms: [
          "fed disorders",
          "an eating disorder",
          "a feeding disorder",
          "",
          "medical conditions",
          "underlying medical conditions",
          "any contributing underlying medical conditions",
        ],
      },
      "feeding problem": {
        labels: "PROBLEM",
        synonyms: [
          "pain",
          "discomfort",
          "reflux",
          "allergy",
          "feeding (pain",
          "coughing",
          "vomiting",
          "gagging",
          "ng tubes",
          "oral procedures",
          "a ventilator",
          "surgeries",
          "slow emptying of the stomach",
          "feeding disorders",
          "",
          "feeding difficulties",
          "the feeding problem",
          "a feeding disorder",
          "your difficulty with feeding foods",
          "feeding problems",
          "his feeding difficulties",
          "her feeding difficulties",
          "cameron's feeding problems",
          "feeding evaluation",
          "her\nfeeding difficulties",
        ],
      },
      plan: {
        labels: "TREATMENT",
        synonyms: [
          "a pediatric feeding  disorders",
          "",
          "treatment plan",
          "a treatment plan",
          "a proposed treatment plan",
        ],
      },
      "specific interventions": {
        labels: "TREATMENT",
        synonyms: [
          "eating disorders",
          "",
          "specific intervention",
          "specific interventions",
          "specific treatments",
        ],
      },
      "specific dietary interventions": {
        labels: "TREATMENT",
        synonyms: [
          "potassium intake",
          "dyslipidemia",
          "",
          "intensive day treatment feeding program",
          "duocal recipe",
          "developmental assessment",
        ],
      },
      "special formulas": { labels: "TREATMENT", synonyms: ["", ""] },
      "positioning during feeding": {
        labels: "TREATMENT",
        synonyms: ["", "", "increased periactin"],
      },
      "behavioral interventions": { labels: "TREATMENT", synonyms: ["", ""] },
      "intensive programs": {
        labels: "TREATMENT",
        synonyms: [
          "",
          "",
          "intensive programs",
          "intensive day treatment",
          "clinical guideline intensive programs",
          "intensive feeding program",
          "those evaluations",
          "the intensive feeding program",
          "an intensive approach",
          "current pediasure",
        ],
      },
      "intensive outpatient programs": {
        labels: "TREATMENT",
        synonyms: ["", "", "outpatient therapy"],
      },
      "severe cases": { labels: "PROBLEM", synonyms: ["covid", ""] },
      malnutrition: {
        labels: "PROBLEM",
        synonyms: [
          "fatigue",
          "dizziness",
          "weight loss",
          "untreated malnutrition",
          "physical or mental disability",
          "short stature",
          "slow growth whole body",
          "water-electrolyte imbalance",
          "muscle weakness",
          "loss of muscle",
          "",
          "nutritional deficiency",
        ],
      },
      "failure to thrive": {
        labels: "PROBLEM",
        synonyms: [
          "vomiting",
          "diarrhea",
          "fussiness",
          "weak cry",
          'stiff or "floppy" muscles',
          "",
        ],
      },
      "unstable electrolyte disorders": {
        labels: "PROBLEM",
        synonyms: [
          "confusion",
          "irritability",
          "diarrhea",
          "constipation",
          "fatigue",
          "headaches",
          "irregular or fast heart rate (arrhythmia",
          "muscle cramps",
          "muscle spasms",
          "weakness",
          "nausea",
          "vomiting",
          "numbness",
          "tingling in limbs, fingers and toes",
          "electrolyte imbalance",
          "",
          "an eval",
        ],
      },
      "serious allergic reactions": {
        labels: "PROBLEM",
        synonyms: [
          "hives",
          "itching",
          "flushed or pale skin",
          "low blood pressure",
          "hypotension",
          "constriction of the airways",
          "a swollen tongue or throat",
          "wheezing",
          "trouble breathing",
          "a weak and rapid pulse",
          "nausea",
          "vomiting",
          "diarrhea",
          "dizziness",
          "fainting",
          "anaphylaxis",
          "",
        ],
      },
      "tube feedings": {
        labels: "TREATMENT",
        synonyms: [
          "a feeding tube",
          "enteral feeding",
          "tube feeding",
          "feeding tube",
          "",
          "tube feeding",
          "tube feeding diet",
          "feeding tube",
          "feeding therapy",
          "tube feedings",
        ],
      },
      "speech therapy": {
        labels: "TREATMENT",
        synonyms: ["", "", "speech therapy"],
      },
      "different treatments": {
        labels: "TREATMENT",
        synonyms: [
          "medication",
          "medicine",
          "regimen",
          "therapy",
          "",
          "an evaluation",
          "thorough medical evaluation",
          "the medical evaluation",
          "this treatment",
          "the treatment",
          "a thorough med eval",
          "extreme preterm",
          "the evaluation",
        ],
      },
      "each therapy": {
        labels: "TREATMENT",
        synonyms: [
          "therapies analysis",
          "healing",
          "medicine",
          "therapeutics",
          "therapies",
          "",
          "estimated length of treatment",
          "noted tx",
        ],
      },
      "individual 's impairments": { labels: "PROBLEM", synonyms: ["", ""] },
      "functional deficits": {
        labels: "PROBLEM",
        synonyms: ["a study", "executive functioning deficits", ""],
      },
      "same plans": { labels: "TREATMENT", synonyms: ["procedure", ""] },
      "": { synonyms: [""] },
    },
  };
}
